# Generated by Django 4.2.7 on 2023-12-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='photos/')),
                ('thumbnail', models.ImageField(editable=False, upload_to='thumbnails/')),
            ],
        ),
    ]
