# Generated by Django 4.2.7 on 2023-12-08 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_title'),
        ('events', '0002_event_title'),
        ('gallery', '0004_alter_photo_image_alter_photo_thumbnail_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.event'),
        ),
        migrations.AlterField(
            model_name='file',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
    ]
