# Generated by Django 4.2.7 on 2023-12-12 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_event_photos'),
        ('projects', '0006_alter_project_type'),
        ('gallery', '0005_alter_file_event_alter_file_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='media/photos/')),
                ('thumbnail', models.ImageField(editable=False, upload_to='media/thumbnails/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_photos', to='events.event')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PhotoProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='media/photos/')),
                ('thumbnail', models.ImageField(editable=False, upload_to='media/thumbnails/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_photos', to='projects.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
