# Generated by Django 4.2.7 on 2023-12-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_photoevent_photoproject_delete_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoevent',
            name='image',
            field=models.ImageField(upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='photoevent',
            name='thumbnail',
            field=models.ImageField(editable=False, upload_to='thumbnails/'),
        ),
        migrations.AlterField(
            model_name='photoproject',
            name='image',
            field=models.ImageField(upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='photoproject',
            name='thumbnail',
            field=models.ImageField(editable=False, upload_to='thumbnails/'),
        ),
    ]
