# Generated by Django 4.2.7 on 2023-12-15 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_project_thumbnail'),
        ('events', '0004_event_cover'),
        ('gallery', '0008_concretephoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_files', to='events.event'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='files'),
        ),
        migrations.AlterField(
            model_name='file',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_files', to='projects.project'),
        ),
    ]
