# Generated by Django 4.2.7 on 2023-12-26 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_project_thumbnail'),
        ('gallery', '0009_alter_file_event_alter_file_file_alter_file_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='project_files', to='projects.project'),
        ),
    ]
