# Generated by Django 4.2.7 on 2023-12-26 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_cover'),
        ('gallery', '0010_alter_file_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='event',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='event_files', to='events.event'),
        ),
    ]
