# Generated by Django 4.2.7 on 2023-11-28 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('place', models.CharField(max_length=150)),
                ('date', models.DateField()),
            ],
        ),
    ]
