# Generated by Django 4.2.7 on 2023-12-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='photos',
            field=models.ManyToManyField(related_name='projects', to='gallery.photo'),
        ),
        migrations.AlterField(
            model_name='project',
            name='place',
            field=models.CharField(max_length=100),
        ),
    ]
