# Generated by Django 4.2.7 on 2023-12-05 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_photos_alter_project_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='photos',
        ),
    ]
