# Generated by Django 4.2.7 on 2023-12-06 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_project_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='title',
            field=models.CharField(default='Example', max_length=50),
        ),
    ]
