# Generated by Django 4.2.7 on 2023-12-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('AR', 'Architecture'), ('UR', 'Urbanism'), ('RE', 'Research'), ('PU', 'Publication'), ('IN', 'Interview'), ('WO', 'Workshop')], default='AR', max_length=2),
        ),
    ]
