# Generated by Django 4.2.7 on 2023-12-12 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('ar', 'Architecture'), ('ur', 'Urbanism'), ('re', 'Research'), ('pu', 'Publication'), ('in', 'Interview'), ('wo', 'Workshop')], default='ar', max_length=2),
        ),
    ]
