# Generated by Django 4.2.7 on 2023-12-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('place', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('photos', models.ManyToManyField(blank=True, related_name='events', to='gallery.photo')),
            ],
        ),
    ]
