# Generated by Django 4.2.7 on 2023-12-08 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='photos',
        ),
    ]
