# Generated by Django 4.2.7 on 2023-12-15 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_event_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='event_covers/'),
        ),
    ]
