# Generated by Django 4.2.7 on 2023-12-03 14:00

from django.db import migrations, models
import members.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_photos_alter_project_place'),
        ('members', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='photo',
            field=models.ImageField(blank=True, upload_to=members.models.user_photo_upload_filename),
        ),
        migrations.AlterField(
            model_name='member',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='members', to='projects.project'),
        ),
    ]
